sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID50ksbMbCOdJv4CbO9pSbrqBZLoskgHYkPmPpBvBsEg tristan-mihai.radulescu@etu.umontpellier.fr
namespace: kubevirt

defaultUsers:
  - name: root
    tmppwd: root
  - name: courtcircuits
    tmppwd: courtcircuits

vms:
  - name: wilt
    dvSource: debian12-dv
    node: diiv
    hostname: wilt
    subdomain: shoebox
    cpu:
      cores: 2
    memory: 512M
    disk:
      size: 10856Mi
    ports:
      - port: 22
        protocol: TCP
        name: ssh
      - port: 80
        protocol: TCP
        name: http
      - port: 443
        protocol: TCP
        name: https
      - port: 389
        protocol: UDP
        name: ldap
      - port: 389
        protocol: tcp
        name: ldaptcp
      - port: 636
        protocol: TCP
        name: ldaps
      - port: 636
        protocol: UDP
        name: ldaps2
