apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: applications
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: prometheus
    targetRevision: 27.52.0
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          persistence:
            storageClass: "longhorn"
        server:
          persistentVolume:
            retention: 15d
            retentionSize: 20Gi
            storageClass: "longhorn"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

