dvs:
  - name: "debian12-dv"
    url: "https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.raw"
    node: "diiv"
    size: "10Gi"
  - name: "wisp-debian12-dv"
    url: "https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.raw"
    node: "wisp"
    size: "10Gi"
