apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-server
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: docker.io/milou666/shoebox-ldap:latest
        ports:
        - containerPort: 389
          name: ldap
          protocol: TCP
        env:
        - name: DEFAULT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-admin-secret
              key: admin-password
        - name: DEFAULT_ORG_DOMAIN
          value: "homelab.local"
        volumeMounts:
        - name: ldap-init
          mountPath: /etc/init.ldif
          subPath: init.ldif
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
      volumes:
      - name: ldap-init
        configMap:
          name: ldap-init-config
