# Default values for ldap chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/milou666/shoebox-ldap
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 389
  targetPort: 389
  protocol: TCP

resources:
  limits:
    cpu: 200m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 1024Mi

# LDAP configuration
ldap:
  # Organization domain for LDAP
  orgDomain: "homelab.local"

  # Admin password (consider using external secrets in production)
  adminPassword: "admin"

  # LDAP initialization configuration
  initLdif: |
    # Define organizational units and example users
    dn: dc=homelab,dc=local
    objectClass: top
    objectClass: dcObject
    objectClass: organization
    o: Homelab
    dc: homelab

    dn: ou=system,dc=homelab,dc=local
    objectClass: organizationalUnit
    ou: system

    dn: ou=people,dc=homelab,dc=local
    objectClass: organizationalUnit
    ou: people

    dn: ou=pamUsers,ou=people,dc=homelab,dc=local
    objectClass: organizationalUnit
    ou: pamUsers

    dn: ou=keycloak,ou=people,dc=homelab,dc=local
    objectClass: organizationalUnit
    ou: keycloak

    dn: ou=groups,dc=homelab,dc=local
    objectClass: organizationalUnit
    ou: groups


# Pod labels
podLabels:
  app: ldap

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
