apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldap.fullname" . }}-config
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
data:
  init.ldif: |
{{ .Values.ldap.initLdif | indent 4 }}
