apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldap.fullname" . }}
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    {{- include "ldap.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}
    name: ldap
